### ISSUE TITLE
[Mac]專案下yarn install出錯

### ISSUE THREAD

**Issue by hikaruKou** [BLOCKCODE-TW/FE_TEMPLATE#2]
error /Users/maola/project/FE_TEMPLATE/node_modules/guetzli: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments: 
Directory: /Users/maola/project/FE_TEMPLATE/node_modules/guetzli
Output:
node:internal/child_process:413
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:700:9)
    at /Users/maola/project/FE_TEMPLATE/node_modules/guetzli/node_modules/bin-check/index.js:22:12
    at /Users/maola/project/FE_TEMPLATE/node_modules/guetzli/node_modules/executable/index.js:27:4
    at FSReqCallback.oncomplete (node:fs:199:5) {
  errno: -86,
  code: 'Unknown system error -86',

**Comment by jaliao** [comment]
```
nvm cache clear
```
